FROM node:19-alpine3.16 as build-stage

WORKDIR /app

COPY package*.json /app/
RUN yarn install --development

COPY . /app/

RUN npx next telemetry disable

RUN yarn run build:local

EXPOSE 3000

ENV NODE_OPTIONS "--max-http-header-size=16834"
ENV NODE_ENV "production"
ENV PORT 3000

CMD [ "node", "server.js" ]